# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/soldatov_a/CLionProjects/messanger_project

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/soldatov_a/CLionProjects/messanger_project/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/soldatov_a/CLionProjects/messanger_project/build/CMakeFiles /Users/soldatov_a/CLionProjects/messanger_project/build//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/soldatov_a/CLionProjects/messanger_project/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named messenger_core

# Build rule for target.
messenger_core: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 messenger_core
.PHONY : messenger_core

# fast build rule for target.
messenger_core/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/messenger_core.dir/build.make CMakeFiles/messenger_core.dir/build
.PHONY : messenger_core/fast

#=============================================================================
# Target rules for targets named target_exec

# Build rule for target.
target_exec: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 target_exec
.PHONY : target_exec

# fast build rule for target.
target_exec/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/target_exec.dir/build.make CMakeFiles/target_exec.dir/build
.PHONY : target_exec/fast

src/chat/ChatClient.o: src/chat/ChatClient.cpp.o
.PHONY : src/chat/ChatClient.o

# target to build an object file
src/chat/ChatClient.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/messenger_core.dir/build.make CMakeFiles/messenger_core.dir/src/chat/ChatClient.cpp.o
.PHONY : src/chat/ChatClient.cpp.o

src/chat/ChatClient.i: src/chat/ChatClient.cpp.i
.PHONY : src/chat/ChatClient.i

# target to preprocess a source file
src/chat/ChatClient.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/messenger_core.dir/build.make CMakeFiles/messenger_core.dir/src/chat/ChatClient.cpp.i
.PHONY : src/chat/ChatClient.cpp.i

src/chat/ChatClient.s: src/chat/ChatClient.cpp.s
.PHONY : src/chat/ChatClient.s

# target to generate assembly for a file
src/chat/ChatClient.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/messenger_core.dir/build.make CMakeFiles/messenger_core.dir/src/chat/ChatClient.cpp.s
.PHONY : src/chat/ChatClient.cpp.s

src/chat/ChatServer.o: src/chat/ChatServer.cpp.o
.PHONY : src/chat/ChatServer.o

# target to build an object file
src/chat/ChatServer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/messenger_core.dir/build.make CMakeFiles/messenger_core.dir/src/chat/ChatServer.cpp.o
.PHONY : src/chat/ChatServer.cpp.o

src/chat/ChatServer.i: src/chat/ChatServer.cpp.i
.PHONY : src/chat/ChatServer.i

# target to preprocess a source file
src/chat/ChatServer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/messenger_core.dir/build.make CMakeFiles/messenger_core.dir/src/chat/ChatServer.cpp.i
.PHONY : src/chat/ChatServer.cpp.i

src/chat/ChatServer.s: src/chat/ChatServer.cpp.s
.PHONY : src/chat/ChatServer.s

# target to generate assembly for a file
src/chat/ChatServer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/messenger_core.dir/build.make CMakeFiles/messenger_core.dir/src/chat/ChatServer.cpp.s
.PHONY : src/chat/ChatServer.cpp.s

src/chat/Message.o: src/chat/Message.cpp.o
.PHONY : src/chat/Message.o

# target to build an object file
src/chat/Message.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/messenger_core.dir/build.make CMakeFiles/messenger_core.dir/src/chat/Message.cpp.o
.PHONY : src/chat/Message.cpp.o

src/chat/Message.i: src/chat/Message.cpp.i
.PHONY : src/chat/Message.i

# target to preprocess a source file
src/chat/Message.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/messenger_core.dir/build.make CMakeFiles/messenger_core.dir/src/chat/Message.cpp.i
.PHONY : src/chat/Message.cpp.i

src/chat/Message.s: src/chat/Message.cpp.s
.PHONY : src/chat/Message.s

# target to generate assembly for a file
src/chat/Message.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/messenger_core.dir/build.make CMakeFiles/messenger_core.dir/src/chat/Message.cpp.s
.PHONY : src/chat/Message.cpp.s

src/chat/main.o: src/chat/main.cpp.o
.PHONY : src/chat/main.o

# target to build an object file
src/chat/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/target_exec.dir/build.make CMakeFiles/target_exec.dir/src/chat/main.cpp.o
.PHONY : src/chat/main.cpp.o

src/chat/main.i: src/chat/main.cpp.i
.PHONY : src/chat/main.i

# target to preprocess a source file
src/chat/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/target_exec.dir/build.make CMakeFiles/target_exec.dir/src/chat/main.cpp.i
.PHONY : src/chat/main.cpp.i

src/chat/main.s: src/chat/main.cpp.s
.PHONY : src/chat/main.s

# target to generate assembly for a file
src/chat/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/target_exec.dir/build.make CMakeFiles/target_exec.dir/src/chat/main.cpp.s
.PHONY : src/chat/main.cpp.s

src/encryption/AES256GCMStrategy.o: src/encryption/AES256GCMStrategy.cpp.o
.PHONY : src/encryption/AES256GCMStrategy.o

# target to build an object file
src/encryption/AES256GCMStrategy.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/messenger_core.dir/build.make CMakeFiles/messenger_core.dir/src/encryption/AES256GCMStrategy.cpp.o
.PHONY : src/encryption/AES256GCMStrategy.cpp.o

src/encryption/AES256GCMStrategy.i: src/encryption/AES256GCMStrategy.cpp.i
.PHONY : src/encryption/AES256GCMStrategy.i

# target to preprocess a source file
src/encryption/AES256GCMStrategy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/messenger_core.dir/build.make CMakeFiles/messenger_core.dir/src/encryption/AES256GCMStrategy.cpp.i
.PHONY : src/encryption/AES256GCMStrategy.cpp.i

src/encryption/AES256GCMStrategy.s: src/encryption/AES256GCMStrategy.cpp.s
.PHONY : src/encryption/AES256GCMStrategy.s

# target to generate assembly for a file
src/encryption/AES256GCMStrategy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/messenger_core.dir/build.make CMakeFiles/messenger_core.dir/src/encryption/AES256GCMStrategy.cpp.s
.PHONY : src/encryption/AES256GCMStrategy.cpp.s

src/encryption/OpenSSLKeyFactory.o: src/encryption/OpenSSLKeyFactory.cpp.o
.PHONY : src/encryption/OpenSSLKeyFactory.o

# target to build an object file
src/encryption/OpenSSLKeyFactory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/messenger_core.dir/build.make CMakeFiles/messenger_core.dir/src/encryption/OpenSSLKeyFactory.cpp.o
.PHONY : src/encryption/OpenSSLKeyFactory.cpp.o

src/encryption/OpenSSLKeyFactory.i: src/encryption/OpenSSLKeyFactory.cpp.i
.PHONY : src/encryption/OpenSSLKeyFactory.i

# target to preprocess a source file
src/encryption/OpenSSLKeyFactory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/messenger_core.dir/build.make CMakeFiles/messenger_core.dir/src/encryption/OpenSSLKeyFactory.cpp.i
.PHONY : src/encryption/OpenSSLKeyFactory.cpp.i

src/encryption/OpenSSLKeyFactory.s: src/encryption/OpenSSLKeyFactory.cpp.s
.PHONY : src/encryption/OpenSSLKeyFactory.s

# target to generate assembly for a file
src/encryption/OpenSSLKeyFactory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/messenger_core.dir/build.make CMakeFiles/messenger_core.dir/src/encryption/OpenSSLKeyFactory.cpp.s
.PHONY : src/encryption/OpenSSLKeyFactory.cpp.s

src/network/MessageProtocol.o: src/network/MessageProtocol.cpp.o
.PHONY : src/network/MessageProtocol.o

# target to build an object file
src/network/MessageProtocol.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/messenger_core.dir/build.make CMakeFiles/messenger_core.dir/src/network/MessageProtocol.cpp.o
.PHONY : src/network/MessageProtocol.cpp.o

src/network/MessageProtocol.i: src/network/MessageProtocol.cpp.i
.PHONY : src/network/MessageProtocol.i

# target to preprocess a source file
src/network/MessageProtocol.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/messenger_core.dir/build.make CMakeFiles/messenger_core.dir/src/network/MessageProtocol.cpp.i
.PHONY : src/network/MessageProtocol.cpp.i

src/network/MessageProtocol.s: src/network/MessageProtocol.cpp.s
.PHONY : src/network/MessageProtocol.s

# target to generate assembly for a file
src/network/MessageProtocol.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/messenger_core.dir/build.make CMakeFiles/messenger_core.dir/src/network/MessageProtocol.cpp.s
.PHONY : src/network/MessageProtocol.cpp.s

src/network/TcpClient.o: src/network/TcpClient.cpp.o
.PHONY : src/network/TcpClient.o

# target to build an object file
src/network/TcpClient.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/messenger_core.dir/build.make CMakeFiles/messenger_core.dir/src/network/TcpClient.cpp.o
.PHONY : src/network/TcpClient.cpp.o

src/network/TcpClient.i: src/network/TcpClient.cpp.i
.PHONY : src/network/TcpClient.i

# target to preprocess a source file
src/network/TcpClient.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/messenger_core.dir/build.make CMakeFiles/messenger_core.dir/src/network/TcpClient.cpp.i
.PHONY : src/network/TcpClient.cpp.i

src/network/TcpClient.s: src/network/TcpClient.cpp.s
.PHONY : src/network/TcpClient.s

# target to generate assembly for a file
src/network/TcpClient.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/messenger_core.dir/build.make CMakeFiles/messenger_core.dir/src/network/TcpClient.cpp.s
.PHONY : src/network/TcpClient.cpp.s

src/network/TcpServer.o: src/network/TcpServer.cpp.o
.PHONY : src/network/TcpServer.o

# target to build an object file
src/network/TcpServer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/messenger_core.dir/build.make CMakeFiles/messenger_core.dir/src/network/TcpServer.cpp.o
.PHONY : src/network/TcpServer.cpp.o

src/network/TcpServer.i: src/network/TcpServer.cpp.i
.PHONY : src/network/TcpServer.i

# target to preprocess a source file
src/network/TcpServer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/messenger_core.dir/build.make CMakeFiles/messenger_core.dir/src/network/TcpServer.cpp.i
.PHONY : src/network/TcpServer.cpp.i

src/network/TcpServer.s: src/network/TcpServer.cpp.s
.PHONY : src/network/TcpServer.s

# target to generate assembly for a file
src/network/TcpServer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/messenger_core.dir/build.make CMakeFiles/messenger_core.dir/src/network/TcpServer.cpp.s
.PHONY : src/network/TcpServer.cpp.s

src/patterns/Command.o: src/patterns/Command.cpp.o
.PHONY : src/patterns/Command.o

# target to build an object file
src/patterns/Command.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/messenger_core.dir/build.make CMakeFiles/messenger_core.dir/src/patterns/Command.cpp.o
.PHONY : src/patterns/Command.cpp.o

src/patterns/Command.i: src/patterns/Command.cpp.i
.PHONY : src/patterns/Command.i

# target to preprocess a source file
src/patterns/Command.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/messenger_core.dir/build.make CMakeFiles/messenger_core.dir/src/patterns/Command.cpp.i
.PHONY : src/patterns/Command.cpp.i

src/patterns/Command.s: src/patterns/Command.cpp.s
.PHONY : src/patterns/Command.s

# target to generate assembly for a file
src/patterns/Command.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/messenger_core.dir/build.make CMakeFiles/messenger_core.dir/src/patterns/Command.cpp.s
.PHONY : src/patterns/Command.cpp.s

src/patterns/Logger.o: src/patterns/Logger.cpp.o
.PHONY : src/patterns/Logger.o

# target to build an object file
src/patterns/Logger.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/messenger_core.dir/build.make CMakeFiles/messenger_core.dir/src/patterns/Logger.cpp.o
.PHONY : src/patterns/Logger.cpp.o

src/patterns/Logger.i: src/patterns/Logger.cpp.i
.PHONY : src/patterns/Logger.i

# target to preprocess a source file
src/patterns/Logger.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/messenger_core.dir/build.make CMakeFiles/messenger_core.dir/src/patterns/Logger.cpp.i
.PHONY : src/patterns/Logger.cpp.i

src/patterns/Logger.s: src/patterns/Logger.cpp.s
.PHONY : src/patterns/Logger.s

# target to generate assembly for a file
src/patterns/Logger.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/messenger_core.dir/build.make CMakeFiles/messenger_core.dir/src/patterns/Logger.cpp.s
.PHONY : src/patterns/Logger.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... messenger_core"
	@echo "... target_exec"
	@echo "... src/chat/ChatClient.o"
	@echo "... src/chat/ChatClient.i"
	@echo "... src/chat/ChatClient.s"
	@echo "... src/chat/ChatServer.o"
	@echo "... src/chat/ChatServer.i"
	@echo "... src/chat/ChatServer.s"
	@echo "... src/chat/Message.o"
	@echo "... src/chat/Message.i"
	@echo "... src/chat/Message.s"
	@echo "... src/chat/main.o"
	@echo "... src/chat/main.i"
	@echo "... src/chat/main.s"
	@echo "... src/encryption/AES256GCMStrategy.o"
	@echo "... src/encryption/AES256GCMStrategy.i"
	@echo "... src/encryption/AES256GCMStrategy.s"
	@echo "... src/encryption/OpenSSLKeyFactory.o"
	@echo "... src/encryption/OpenSSLKeyFactory.i"
	@echo "... src/encryption/OpenSSLKeyFactory.s"
	@echo "... src/network/MessageProtocol.o"
	@echo "... src/network/MessageProtocol.i"
	@echo "... src/network/MessageProtocol.s"
	@echo "... src/network/TcpClient.o"
	@echo "... src/network/TcpClient.i"
	@echo "... src/network/TcpClient.s"
	@echo "... src/network/TcpServer.o"
	@echo "... src/network/TcpServer.i"
	@echo "... src/network/TcpServer.s"
	@echo "... src/patterns/Command.o"
	@echo "... src/patterns/Command.i"
	@echo "... src/patterns/Command.s"
	@echo "... src/patterns/Logger.o"
	@echo "... src/patterns/Logger.i"
	@echo "... src/patterns/Logger.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

