# CMake generated Testfile for 
# Source directory: /Users/soldatov_a/CLionProjects/messanger_project/tests
# Build directory: /Users/soldatov_a/CLionProjects/messanger_project/build-tests/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_message "/Users/soldatov_a/CLionProjects/messanger_project/build-tests/tests/test_message")
set_tests_properties(test_message PROPERTIES  _BACKTRACE_TRIPLES "/Users/soldatov_a/CLionProjects/messanger_project/tests/CMakeLists.txt;24;add_test;/Users/soldatov_a/CLionProjects/messanger_project/tests/CMakeLists.txt;27;add_evlampy_unit_test;/Users/soldatov_a/CLionProjects/messanger_project/tests/CMakeLists.txt;0;")
add_test(test_message_protocol "/Users/soldatov_a/CLionProjects/messanger_project/build-tests/tests/test_message_protocol")
set_tests_properties(test_message_protocol PROPERTIES  _BACKTRACE_TRIPLES "/Users/soldatov_a/CLionProjects/messanger_project/tests/CMakeLists.txt;24;add_test;/Users/soldatov_a/CLionProjects/messanger_project/tests/CMakeLists.txt;31;add_evlampy_unit_test;/Users/soldatov_a/CLionProjects/messanger_project/tests/CMakeLists.txt;0;")
add_test(test_tcp_server "/Users/soldatov_a/CLionProjects/messanger_project/build-tests/tests/test_tcp_server")
set_tests_properties(test_tcp_server PROPERTIES  _BACKTRACE_TRIPLES "/Users/soldatov_a/CLionProjects/messanger_project/tests/CMakeLists.txt;24;add_test;/Users/soldatov_a/CLionProjects/messanger_project/tests/CMakeLists.txt;35;add_evlampy_unit_test;/Users/soldatov_a/CLionProjects/messanger_project/tests/CMakeLists.txt;0;")
add_test(test_tcp_client "/Users/soldatov_a/CLionProjects/messanger_project/build-tests/tests/test_tcp_client")
set_tests_properties(test_tcp_client PROPERTIES  _BACKTRACE_TRIPLES "/Users/soldatov_a/CLionProjects/messanger_project/tests/CMakeLists.txt;24;add_test;/Users/soldatov_a/CLionProjects/messanger_project/tests/CMakeLists.txt;39;add_evlampy_unit_test;/Users/soldatov_a/CLionProjects/messanger_project/tests/CMakeLists.txt;0;")
add_test(test_encryption_aes "/Users/soldatov_a/CLionProjects/messanger_project/build-tests/tests/test_encryption_aes")
set_tests_properties(test_encryption_aes PROPERTIES  _BACKTRACE_TRIPLES "/Users/soldatov_a/CLionProjects/messanger_project/tests/CMakeLists.txt;24;add_test;/Users/soldatov_a/CLionProjects/messanger_project/tests/CMakeLists.txt;43;add_evlampy_unit_test;/Users/soldatov_a/CLionProjects/messanger_project/tests/CMakeLists.txt;0;")
add_test(test_encryption_key_factory "/Users/soldatov_a/CLionProjects/messanger_project/build-tests/tests/test_encryption_key_factory")
set_tests_properties(test_encryption_key_factory PROPERTIES  _BACKTRACE_TRIPLES "/Users/soldatov_a/CLionProjects/messanger_project/tests/CMakeLists.txt;24;add_test;/Users/soldatov_a/CLionProjects/messanger_project/tests/CMakeLists.txt;47;add_evlampy_unit_test;/Users/soldatov_a/CLionProjects/messanger_project/tests/CMakeLists.txt;0;")
add_test(test_chat_server "/Users/soldatov_a/CLionProjects/messanger_project/build-tests/tests/test_chat_server")
set_tests_properties(test_chat_server PROPERTIES  _BACKTRACE_TRIPLES "/Users/soldatov_a/CLionProjects/messanger_project/tests/CMakeLists.txt;24;add_test;/Users/soldatov_a/CLionProjects/messanger_project/tests/CMakeLists.txt;51;add_evlampy_unit_test;/Users/soldatov_a/CLionProjects/messanger_project/tests/CMakeLists.txt;0;")
add_test(test_chat_client "/Users/soldatov_a/CLionProjects/messanger_project/build-tests/tests/test_chat_client")
set_tests_properties(test_chat_client PROPERTIES  _BACKTRACE_TRIPLES "/Users/soldatov_a/CLionProjects/messanger_project/tests/CMakeLists.txt;24;add_test;/Users/soldatov_a/CLionProjects/messanger_project/tests/CMakeLists.txt;55;add_evlampy_unit_test;/Users/soldatov_a/CLionProjects/messanger_project/tests/CMakeLists.txt;0;")
add_test(test_patterns_observer "/Users/soldatov_a/CLionProjects/messanger_project/build-tests/tests/test_patterns_observer")
set_tests_properties(test_patterns_observer PROPERTIES  _BACKTRACE_TRIPLES "/Users/soldatov_a/CLionProjects/messanger_project/tests/CMakeLists.txt;24;add_test;/Users/soldatov_a/CLionProjects/messanger_project/tests/CMakeLists.txt;59;add_evlampy_unit_test;/Users/soldatov_a/CLionProjects/messanger_project/tests/CMakeLists.txt;0;")
add_test(test_patterns_command_logger "/Users/soldatov_a/CLionProjects/messanger_project/build-tests/tests/test_patterns_command_logger")
set_tests_properties(test_patterns_command_logger PROPERTIES  _BACKTRACE_TRIPLES "/Users/soldatov_a/CLionProjects/messanger_project/tests/CMakeLists.txt;24;add_test;/Users/soldatov_a/CLionProjects/messanger_project/tests/CMakeLists.txt;63;add_evlampy_unit_test;/Users/soldatov_a/CLionProjects/messanger_project/tests/CMakeLists.txt;0;")
add_test(scenario_auth_flow "/Users/soldatov_a/CLionProjects/messanger_project/build-tests/tests/scenario_auth_flow")
set_tests_properties(scenario_auth_flow PROPERTIES  _BACKTRACE_TRIPLES "/Users/soldatov_a/CLionProjects/messanger_project/tests/CMakeLists.txt;75;add_test;/Users/soldatov_a/CLionProjects/messanger_project/tests/CMakeLists.txt;78;add_evlampy_scenario;/Users/soldatov_a/CLionProjects/messanger_project/tests/CMakeLists.txt;0;")
add_test(scenario_direct_message "/Users/soldatov_a/CLionProjects/messanger_project/build-tests/tests/scenario_direct_message")
set_tests_properties(scenario_direct_message PROPERTIES  _BACKTRACE_TRIPLES "/Users/soldatov_a/CLionProjects/messanger_project/tests/CMakeLists.txt;75;add_test;/Users/soldatov_a/CLionProjects/messanger_project/tests/CMakeLists.txt;79;add_evlampy_scenario;/Users/soldatov_a/CLionProjects/messanger_project/tests/CMakeLists.txt;0;")
add_test(scenario_group_flow "/Users/soldatov_a/CLionProjects/messanger_project/build-tests/tests/scenario_group_flow")
set_tests_properties(scenario_group_flow PROPERTIES  _BACKTRACE_TRIPLES "/Users/soldatov_a/CLionProjects/messanger_project/tests/CMakeLists.txt;75;add_test;/Users/soldatov_a/CLionProjects/messanger_project/tests/CMakeLists.txt;80;add_evlampy_scenario;/Users/soldatov_a/CLionProjects/messanger_project/tests/CMakeLists.txt;0;")
add_test(scenario_delete_for_all "/Users/soldatov_a/CLionProjects/messanger_project/build-tests/tests/scenario_delete_for_all")
set_tests_properties(scenario_delete_for_all PROPERTIES  _BACKTRACE_TRIPLES "/Users/soldatov_a/CLionProjects/messanger_project/tests/CMakeLists.txt;75;add_test;/Users/soldatov_a/CLionProjects/messanger_project/tests/CMakeLists.txt;81;add_evlampy_scenario;/Users/soldatov_a/CLionProjects/messanger_project/tests/CMakeLists.txt;0;")
add_test(scenario_admin_actions "/Users/soldatov_a/CLionProjects/messanger_project/build-tests/tests/scenario_admin_actions")
set_tests_properties(scenario_admin_actions PROPERTIES  _BACKTRACE_TRIPLES "/Users/soldatov_a/CLionProjects/messanger_project/tests/CMakeLists.txt;75;add_test;/Users/soldatov_a/CLionProjects/messanger_project/tests/CMakeLists.txt;82;add_evlampy_scenario;/Users/soldatov_a/CLionProjects/messanger_project/tests/CMakeLists.txt;0;")
add_test(scenario_persistence_relogin "/Users/soldatov_a/CLionProjects/messanger_project/build-tests/tests/scenario_persistence_relogin")
set_tests_properties(scenario_persistence_relogin PROPERTIES  _BACKTRACE_TRIPLES "/Users/soldatov_a/CLionProjects/messanger_project/tests/CMakeLists.txt;75;add_test;/Users/soldatov_a/CLionProjects/messanger_project/tests/CMakeLists.txt;83;add_evlampy_scenario;/Users/soldatov_a/CLionProjects/messanger_project/tests/CMakeLists.txt;0;")
subdirs("../_deps/googletest-build")
